### ISSUE TITLE
Add XCSoar to manufacturer list

### ISSUE THREAD

**Issue by rawtaz** [ezgliding/goigc#30]
I noticed the list of manufacturers does not include XCSoar. While this is of course proper according to the IGC specification, the fact is that there's *a lot* of XCSoar users out there.

XCSoar produce IGC files just fine, the main difference is that they are not signed with a valid IGC signature. But that's a completely different matter than the file containing otherwise valid IGC data and being a proper flight log.

For this reason I think that XCSoar should be part of the list as well, so that this library can identify XCSoar IGC files as well. The manufacturer ID for XCSoar is simply "XCS" and it does add a HFFTYFRTYPE line as well in the IGC file.

Let me know if you have any questions on this, I have access to IGC files produced by XCSoar.

**Comment by rochaporto** [comment]
Sounds fair enough, i'll pick this up.

If you can attach a sample here i'll test against it.

**Comment by rawtaz** [comment]
Will this work for you? `HFFTYFRTYPE:XCSOAR,XCSOAR Linux 7.0_preview10 Apr 15 2017`

If you need a full log file I can probably get that, just have to search for one online as I don't use XCSoar personally.
